classes:

  Category:
    columns:
      id:   ~
      name: { type: varchar, required: true, primaryString: true }
    propel_behaviors:
      timestampable: ~
      sluggable:     ~

  Product:
    columns:
      id:          ~
      name:        { type: varchar, required: true, primaryString: true }
      category_id: { type: integer, required: true, foreignClass: Category, foreignReference: id, onDelete: cascade }
      price:       { type: float, scale: 2, size: 5, required: true }
    propel_behaviors:
      timestampable: ~
      sluggable:     ~